### ISSUE TITLE
#include <Crc16.h> is missing?

### ISSUE THREAD

**Issue by richmondgingingon** [sglvladi/meshquitto#3]
I have connected my esp8266 but when I compile the code, it shows this library is missing.

**Comment by sglvladi** [comment]
@rgingingon CRC16 is an external library used to detect Software Serial transmission errors.  The library can be found [here](https://github.com/vinmenn/Crc16). This is also mentioned in the README.md file.

Since meshquitto uses a number of external libraries, I would advise you to have a read through the README.md (or the repository homepage), where all information regarding the necessary libraries can be found.

Hope this helps!

**Comment by sglvladi** [comment]
@rgingingon Did the above solve your problem? Should we close the issue?
